// src/config.js - All constants and default configuration data for the game.

// Main stat types for players and monsters
export const StatType = {
    STRENGTH: 'STR',      // Strength: Physical attack power, physical defense
    DEXTERITY: 'DEX',     // Dexterity: Evasion rate, hit chance, physical attack power
    CONSTITUTION: 'CON',  // Constitution: Max HP, defense
    INTELLIGENCE: 'INT',  // Intelligence: Magic attack power, max MP
    WISDOM: 'WIS',        // Wisdom: Magic defense, some spell efficiency
    CHARISMA: 'CHA'       // Charisma: Interactions, some spell efficiency
};

// Default race settings
export const RACES = [
    { name: 'Human', attr_bonus: {}},
    { name: 'Elf', attr_bonus: { DEX: 2, INT: 1 }}, // Elves get a bonus to Dexterity and Intelligence
    { name: 'Dwarf', attr_bonus: { STR: 1, CON: 2 }},
    { name: 'Orc', attr_bonus: { STR: 3 }},
    { name: 'Goblin', attr_bonus: { DEX: 2 }},
    { name: 'Gnome', attr_bonus: { INT: 2 }},
    { name: 'Undead', attr_bonus: { CON: 2 }},
    { name: 'Centaur', attr_bonus: { STR: 1, DEX: 1 }},
    { name: 'Dragonborn', attr_bonus: { STR: 1, CHA: 1 }},
    { name: 'Tiefling', attr_bonus: { INT: 1, CHA: 1 }}
];

// Default class settings
export const CLASSES = [
    { name: 'Warrior', attr_priority: [StatType.STRENGTH, StatType.CONSTITUTION] },
    { name: 'Mage', attr_priority: [StatType.INTELLIGENCE] },
    { name: 'Rogue', attr_priority: [StatType.DEXTERITY, StatType.CHARISMA] },
    { name: 'Cleric', attr_priority: [StatType.WISDOM, StatType.CONSTITUTION] },
    { name: 'Bard', attr_priority: [StatType.CHARISMA, StatType.DEXTERITY] },
    { name: 'Paladin', attr_priority: [StatType.STRENGTH, StatType.CHARISMA] },
    { name: 'Ranger', attr_priority: [StatType.DEXTERITY, StatType.WISDOM] },
    { name: 'Monk', attr_priority: [StatType.DEXTERITY, StatType.WISDOM] }
];

// Base monster types and stats (can be dynamically generated by LLM later)
export const MONSTERS = [
    { name: 'Goblin', base_stats: { HP: 20, STR: 5, DEX: 8, CON: 5, INT: 3, WIS: 3, CHA: 3 }, base_exp: 10, drop_chance: 0.5 },
    { name: 'Orc', base_stats: { HP: 40, STR: 10, DEX: 6, CON: 8, INT: 2, WIS: 2, CHA: 2 }, base_exp: 25, drop_chance: 0.6 },
    { name: 'Slime', base_stats: { HP: 15, STR: 3, DEX: 3, CON: 10, INT: 1, WIS: 1, CHA: 1 }, base_exp: 8, drop_chance: 0.4 },
    { name: 'Dire Wolf', base_stats: { HP: 30, STR: 8, DEX: 10, CON: 6, INT: 4, WIS: 4, CHA: 4 }, base_exp: 20, drop_chance: 0.55 }
];

// Item types (detailed properties can be generated by LLM)
export const ItemType = {
    WEAPON: 'Weapon',
    ARMOR: 'Armor',
    POTION: 'Potion',
    MISC: 'Miscellaneous'
};

// Base experience needed to level up (example of linear progression)
// In a real game, this could follow a more complex curve.
export const BASE_EXP_TO_LEVEL_UP = 100;
export const EXP_PER_LEVEL_MULTIPLIER = 1.5; // Growth rate of required EXP per level

// Game constants
export const GAME_CONSTANTS = {
    BASE_HIT_CHANCE: 90,        // Base hit chance (%)
    BASE_EVASION_RATE: 5,       // Base evasion rate (%)
    BASE_CRITICAL_CHANCE: 5,    // Base critical hit chance (%)
    CRITICAL_MULTIPLIER: 1.5,   // Critical hit damage multiplier

    PLAYER_BASE_HP: 15,         // Player's base starting HP
    PLAYER_BASE_MP: 10,         // Player's base starting MP
};

// Logging levels
export const LOG_LEVELS = {
    INFO: 'INFO',
    DEBUG: 'DEBUG',
    WARN: 'WARN',
    ERROR: 'ERROR'
};

// Player's default starting stats
export const DEFAULT_PLAYER_STATS = {
    [StatType.STRENGTH]: 10,
    [StatType.DEXTERITY]: 10,
    [StatType.CONSTITUTION]: 10,
    [StatType.INTELLIGENCE]: 10,
    [StatType.WISDOM]: 10,
    [StatType.CHARISMA]: 10
};

// Player's default base HP (used in player.js)
export const DEFAULT_PLAYER_BASE_HP = GAME_CONSTANTS.PLAYER_BASE_HP;